#!/bin/sh
BINDIR=$(dirname "$0")
export PYTHONPATH=$PYTHONPATH:"$BINDIR/../lib/invesalius"
export INVESALIUS_LIBRARY_PATH="$BINDIR/../share/invesalius"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$BINDIR/../lib/libblas/":"$BINDIR/../lib/lapack/"
cd $INVESALIUS_LIBRARY_PATH
python app.py $@
